# Generated by Django 2.1 on 2018-11-24 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('NUMBER', 'Number'), ('OBJECT', 'Object'), ('STRING', 'String')], max_length=10)),
                ('value', models.TextField()),
                ('key', models.CharField(max_length=255)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('kind', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('NUMBER', 'Number'), ('OBJECT', 'Object'), ('STRING', 'String')], max_length=10)),
                ('value', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('auth_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='override',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Site'),
        ),
        migrations.AddField(
            model_name='kind',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Site'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['site', 'user_id'], name='site_user_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['user_id'], name='user_id_idx'),
        ),
    ]
